### ISSUE TITLE
A wrong parameter name is used

### ISSUE THREAD

**Issue by therter** [clarity-h2020/csis-helpers-module#15]
The parameter emission_scenario is used instead of emissions_scenario

**Comment by DenoBeno** [comment]
hm, I wonder which one is "correct".
Whatever, let's just keep it as is now.

**Comment by p-a-s-c-a-l** [comment]
`emissions_scenario` is correct. It should be used in CSSIS Helpers module, too. There it is called `emission_scenario`.
