### ISSUE TITLE
Add boolean field for Adaptation Project into $StudyInfo

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/csis-helpers-module#23]
Since we want to remove the `Study variant` fieldfrom the Study Scenario object, we need to add it separately to the `$studyInfo` object, so that the Map and Table components can query and filter data for the **baseline** and for the **adapted** scenario.
Boolean field `has_adapted_scenario` will be set based on whether or not the Study contains an "Adaptation Project" Group node.

In the process the `study_variant` attribute will be removed from the `study_scenarios `and `study_presets `of the `$studyInfo` object.

**Comment by patrickkaleta** [comment]
FYI: @p-a-s-c-a-l and @therter 
This is now available on DEV for further testing. **study_variant** is now gone from the `study_scenarios` and `study_presets` and instead has its own boolean field called  `has_adapted_scenario` inside the `$studyInfo` object.

![adapted_scenario](https://user-images.githubusercontent.com/42167036/87400457-1fb81200-c5b9-11ea-8e6e-c5b3f4cb69ee.png)

**Comment by p-a-s-c-a-l** [comment]
Implemented in https://github.com/clarity-h2020/map-component/issues/100
