### ISSUE TITLE
Get Node UUID

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-helpers-module#5]
CSIS Helper Modules retrieved the id of the node which is fine for Legacy REST API, but for making requests to the JSON:API (e.g. GET '/jsonapi/node/report_image/ff1f3c94-abbd-43bc-90d8-c61e7dad6dac/') we need the UUID.

**Comment by therter** [comment]
@fgeyer16  I need also the UUID to requesting the study with the new version of the json-API.

**Comment by fgeyer16** [comment]
I added the uuid of study and step to the csisHelpers.entityinfo object.
You can get them by  csisHelpers.entityinfo.study_uuid and  csisHelpers.entityinfo.step_uuid
