### ISSUE TITLE
Theme Missing

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-helpers-module#7]
Not sure what this error message wants to tell me:

![grafik](https://user-images.githubusercontent.com/1788226/56188222-358cff00-6025-11e9-80f0-342ee30920c6.png)

**Comment by patrickkaleta** [comment]
This was probably caused by a typo, since it was looking for **cisis**... instead of **csis**...
I fixed that typo. This error message should disappear now
