### ISSUE TITLE
Include In Report Button not working properly

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-helpers-module#9]
- The ["Include in Report" Button](https://github.com/clarity-h2020/docker-drupal/issues/46#issuecomment-509161855) does not work for the [Study Area Map]().
- Layers shown on the map are not available in the report image generated with [html2canvas](https://github.com/niklasvh/html2canvas/). This is most likely a problem caused by html2canvas itself and not by the map component or the include in report button.

To track down the problem, the debug log in html2canvas can be used. The problem related to the missing map layers could be resolved by updating html2canvas to the latest version and by changing some [configuration options](https://github.com/niklasvh/html2canvas/issues/153#issuecomment-13267489) or modifying the [react JS Code](https://github.com/niklasvh/html2canvas/issues/567#issuecomment-351003993) of the map component.

**Comment by p-a-s-c-a-l** [comment]
Most likely a CORS problem. See https://github.com/clarity-h2020/emikat/issues/14 and https://github.com/clarity-h2020/data-package/issues/31

**Comment by therter** [comment]
Current status:
When we use html2canvas version 1.0.0-rc1, set the options useCORS and foreignObjectRendering to true and additional ensure that the page is not scrolled down,  then the Report button will work in Chrome.
But the button does not work in Firefox, because the option foreignObjectRendering is not supported by Firefox and without the option foreignObjectRendering, the overlay layers will be clipped.

**Comment by p-a-s-c-a-l** [comment]
> ensure that the page is not scrolled down

how?

**Comment by therter** [comment]
> how?

we can set the page to the top position by execute 
window.scrollTo(0, 0);
After a click on the report button, a popup will open. So the change of the viewport should not disturb the users.

**Comment by patrickkaleta** [comment]
> * The ["Include in Report" Button](https://github.com/clarity-h2020/docker-drupal/issues/46#issuecomment-509161855) does not work for the Study Area Map.

Same bug also mentioned [here](https://github.com/clarity-h2020/csis-helpers-module/issues/13#issuecomment-528797936).

Problem is that the JSON:API and the Group module sometimes have troubles working together (issue described [here](https://www.drupal.org/node/2872645)). Most of the times this is not an issue for us, since we already have a GL-step relation to the Study group, which we can use to create the required relation between the Report image and the Study a different way (this is done via the `csis_helpers_node_insert` hook in the [csis_helpers.module](https://github.com/clarity-h2020/csis-helpers-module/blob/dev/csis_helpers.module)).
**Only place where it doesn't work is the [Study area tab](https://csis.myclimateservice.eu/study/1/view/area), since it does not have a GL-step.** 


Today someone finally found a [workaround](https://www.drupal.org/project/group/issues/2872645#comment-13257188), which makes it possible to send a POST request via JSON:API to create a new Group content. I implemented the necessary function in my latest [commit](https://github.com/clarity-h2020/csis-helpers-module/commit/f44ee39c2409ff05445b5556f1623e2154ab6009), but further testing is needed.

**Note:** The proposed patch #26 in the linked issue does not solve our problem and breaks the entire Study, so it's not an option for us!

**Comment by patrickkaleta** [comment]
> * The ["Include in Report" Button](https://github.com/clarity-h2020/docker-drupal/issues/46#issuecomment-509161855) does not work for the Study Area Map.

This is fixed now. I applied the proposed patch (workaround) from [here](https://www.drupal.org/project/group/issues/2872645#comment-13257188) and so far I haven't detected any unwanted side-effects.

**Comment by p-a-s-c-a-l** [comment]
I tried the 'include in report'-button with the new [table component iframe](https://csis.myclimateservice.eu/study/1/step/83/view/table), but it didn't work:

`TypeError: A is undefined
html2canvas.min.js:6:146514`

**Comment by therter** [comment]
The wrong element is used by html2canvas. I should be able to fix this

**Comment by DenoBeno** [comment]
Excellent. :-)

**Comment by therter** [comment]
Since the html2canvas cannot handle iframes, the first div element of the table component should be used to create the image. So the [csis helper module](https://github.com/clarity-h2020/csis-helpers-module/blob/dev/js/csis_include_in_report.js) must ensure that a valid element will be delivered to html2canvas. 

If the created image does not look like expected, then it is possible that the page uses some css properties, which are not supported. An uncomplete list of supported and not supported css properties can be found [here](https://html2canvas.hertzen.com/features). Sometimes they can be replaced by other css properties.

**Comment by p-a-s-c-a-l** [comment]
The feature is still not working properly for the map component (neither chrome nor firefox):

![grafik](https://user-images.githubusercontent.com/1788226/65604870-757ae980-dfa8-11e9-9524-f00971f80a1d.png)

**Comment by therter** [comment]
It is working now for the map and the table (at least in firefox and chrome) 

![Bildschirmfoto vom 2019-09-25 19-26-08](https://user-images.githubusercontent.com/1788509/65628349-9277e280-dfd1-11e9-8a1e-7bf1d0c07830.png)

![Bildschirmfoto vom 2019-09-25 19-24-56](https://user-images.githubusercontent.com/1788509/65628356-960b6980-dfd1-11e9-9c0c-2924efa3eb09.png)

I think we can close this issue now.

**Comment by p-a-s-c-a-l** [comment]
MCDA App Report image messed up in Chrome: CSS is missing.

![grafik](https://user-images.githubusercontent.com/1788226/66385289-8839e900-e9c0-11e9-8cb0-d6dc11daf693.png)

@therter any idea what's going on here?

**Comment by therter** [comment]
The stylesheets will be loaded in chrome, if the html2canvas option foreignObjectRendering is activated. But some images will not be drawn. 
The option foreignObjectRendering should not be activated in firefox, because firefox does not support this feature.

**Comment by p-a-s-c-a-l** [comment]
> But some images will not be drawn.

Some or all? Which ones? Why?

**Comment by DenoBeno** [comment]
I'm lost here... In my experience, taking screenshots works for the maps & tables & at least some of the widgets in scenario analysis (didn't test them all). It doesn't work for EEA app.

**Comment by p-a-s-c-a-l** [comment]
The screenshot functionality is still very unreliable. @therter which html2canvas version are we using? Did you upgrade to [v1.0.0-rc.5](https://github.com/niklasvh/html2canvas/releases/tag/v1.0.0-rc.5)?

**Comment by therter** [comment]
> Did you upgrade to [v1.0.0-rc.5](https://github.com/niklasvh/html2canvas/releases/tag/v1.0.0-rc.5)?

At the moment, rc.1 is used, because the newer versions ignore the overlay layers of the maps.

**Comment by therter** [comment]
Current State:
At the moment, the html2canvas version v1.0.0-rc.1 is used. But there are some problems with this version:

- The css property transform does no work, if the value uses translate3d with negative values. But this property can be replaced by the top and left property.

- The opacity property does not work, if the value is 0.0. So this property should be replaced by visibility: hidden.

- Stylesheets from iframes will not be loaded in Chrome. This problem does not exist when the foreignObjectRendering mode is used or the href attribute of the style tags is explicitly set.

- custom fonts will not be loaded in Firefox

**Note:** The css changes should be made on a copy of the div element that should be converted to an image to prevent failures after the conversion of the div to an image. For this reason, the html2canvas parameter onclone can take a callback function that allows you to make changes on a copy of the div that should be converted. 

Another problem are SVG images. SVG images will be ignored in chrome, if the html2canvas parameter foreignObjectRendering is not set (but the foreignObjectRendering mode does not work in Firefox).
The foreignObjectRendering mode has some restrictions:
- images will only be rendered, if the base64 image encoding is used. So the images should be converted before html2canvas is used.
- The onclone callback function will not be invoked. 

**The newer versions of html2canvas v1.0.0-rc.2+ have the following problems:**

- overlay layers of the map will not be drawn and I don't know why.
- Stylesheets from iframes will not be loaded in Chrome. This problem does not exist when the foreignObjectRendering mode is used or the href attribute of the style tags is explicitly set.
- if foreignObjectRendering is used, the left side of the image is cut off. 
- custom fonts will not be loaded in Chrome and Firefox

**Comment by p-a-s-c-a-l** [comment]
@therter Please report on the status of the report generation for the following integrated apps:

- [x] [EE Urban Adaptation Viewer](https://github.com/clarity-h2020/csis/issues/60)
- [x] [Scenario Analysis App](https://github.com/clarity-h2020/scenario-analysis/issues/3#issuecomment-542056118)
- [x] [Simple Table Component](https://github.com/clarity-h2020/simple-table-component/)

We are still not sure whether and under which circumstances it's working or not working.

**Comment by therter** [comment]
The report generation is working now for the tables, maps, Scenario Analysis App and the eea App.

**Comment by p-a-s-c-a-l** [comment]
Include Report Button is not visible for non-admin users.

**Comment by patrickkaleta** [comment]
> Include Report Button is not visible for non-admin users.

I'm guessing you're talking about those buttons in the general "Study" Step (e.g. https://csis.myclimateservice.eu/study/55/view/area) for ordinary team members (**so not the owners**). For those users the "Include in report" was hidden due to the discussions in the [User/group Permissions issue](https://github.com/clarity-h2020/csis/issues/114).

But you're right. Even though members cannot edit anything high-level (so anything in the "Study" step), they should still be able to at least take a screenshot of those things. I fixed that and the button is now visible there for ordinary team members.

**Comment by DenoBeno** [comment]
Good

Patrick Kaleta <notifications@github.com> schrieb am Fr., 17. Jan. 2020,
10:13:

**Comment by p-a-s-c-a-l** [comment]
Getting

```js
Uncaught TypeError: Cannot read property 'getElementById' of null
    at HTMLButtonElement.<anonymous> (js_G7lmQBqjZHSWK9IX7Avj9xZS4PdGx6x03vpb7BfP-vU.js:3463)
    at HTMLButtonElement.dispatch (js_VN7rwrZCfKyapY1QuY241S22w6myG2_M6JuGNsj-3Lc.js:3)
    at HTMLButtonElement.q.handle (js_VN7rwrZCfKyapY1QuY241S22w6myG2_M6JuGNsj-3Lc.js:3)
```
when trying to use the include in report feature on [this page](https://csis.myclimateservice.eu/study/55/step/1952/view/maps) to create a screenshot of the [Transport Application](https://github.com/clarity-h2020/csis/issues/134#issuecomment-577601007) embedded [as iFrame](https://github.com/clarity-h2020/csis/issues/122).

**Comment by therter** [comment]
> when trying to use the include in report feature on [this page](https://csis.myclimateservice.eu/study/55/step/1952/view/maps) to create a screenshot of the [Transport Application](https://github.com/clarity-h2020/csis/issues/134#issuecomment-577601007) embedded [as iFrame](https://github.com/clarity-h2020/csis/issues/122).

I will have a look on it

**Comment by therter** [comment]
@ghilbrae  @luis-meteogrid  In order to allow the creation of screenshots, the X-Frame-Option SAMEORIGIN should be removed from the [Transport Application](https://github.com/clarity-h2020/csis/issues/134) (this was also mentioned [here](https://github.com/clarity-h2020/csis/issues/122#issuecomment-577859286)) and the Access-Control-Allow-Origin header should be set to allow  the site https://csis.myclimateservice.eu to access the Transport Application.

**Comment by ghilbrae** [comment]
ACK.

I'm adding my colleague @rapto to the discussion so he is also aware of this.

> @ghilbrae @luis-meteogrid In order to allow the creation of screenshots, the X-Frame-Option SAMEORIGIN should be removed from the [Transport Application](https://github.com/clarity-h2020/csis/issues/134) (this was also mentioned [here](https://github.com/clarity-h2020/csis/issues/122#issuecomment-577859286)) and the Access-Control-Allow-Origin header should be set to allow the site https://csis.myclimateservice.eu to access the Transport Application.

**Comment by ghilbrae** [comment]
The generation of the report/summary has been discussed here: https://github.com/clarity-h2020/csis/issues/134#issuecomment-577590718 and we think that the best option is for us to generate a PDF and send it to the CSIS when it is needed, i.e., when the user wants to generate a Summary. 

I think this would make this point moot, isn't it?

**Comment by therter** [comment]
> The generation of the report/summary has been discussed here: [clarity-h2020/csis#134 (comment)](https://github.com/clarity-h2020/csis/issues/134#issuecomment-577590718) and we think that the best option is for us to generate a PDF and send it to the CSIS when it is needed, i.e., when the user wants to generate a Summary.
> 
> I think this would make this point moot, isn't it?

Yes, that is right

**Comment by p-a-s-c-a-l** [comment]
resolved

**Comment by p-a-s-c-a-l** [comment]
Just another **SHOWSTOPPER** for [CSIS Public BETA Release](https://github.com/clarity-h2020/csis/issues/145): No include in report button for [Scenario Analysis](https://csis.myclimateservice.eu/study/33/step/1517/view/scenario-analysis):

![grafik](https://user-images.githubusercontent.com/1788226/75351855-16980400-58a9-11ea-8f38-0e199bb7790d.png)

AFAIR this used to work @therter ?

**Comment by therter** [comment]
> AFAIR this used to work

Yes, this was working and it is working again. I have added the button via "Manage display".

**Comment by patrickkaleta** [comment]
> > AFAIR this used to work
> 
> Yes, this was working and it is working again. I have added the button via "Manage display".

I remember it working a couple of weeks/months ago. But if I recall correctly, it didn't use the "include in report" button on the bottom of the page (the one @therter just added back into the tab), but instead it had multiple "include" buttons directly inside the app (and that's why, when you go on the Summary and open the "Attached Scenario analysis" you'll see just individual graphs instead of the whole component).

**Comment by p-a-s-c-a-l** [comment]
> instead it had multiple "include" buttons directly inside the app (and that's why, when you go on the Summary and open the "Attached Scenario analysis" you'll see just individual graphs instead of the whole component).

Yes, that never worked reliably, therefore we had to disable it. 
But perhaps we can add several include in report buttons for different parts the iFramed application?

for Scenario Analysis App we would just need atm the table and the bar charts. So if I add a unique id to the respective DIV elements, this *should*  be possible @therter ?

![grafik](https://user-images.githubusercontent.com/1788226/75526149-83c6a900-5a11-11ea-9570-3650a821342a.png)

**Comment by therter** [comment]
>  So if I add a unique id to the respective DIV elements, this _should_ be possible @therter ?

Yes, this should then be possible. At least from the html2canvas side. But we need additional buttons and I don't know, how this buttons can be added.

**Comment by p-a-s-c-a-l** [comment]
The button is configured [here](https://csis.myclimateservice.eu/admin/structure/types/manage/gl_step/display/sce) in the respective GL Step, but I couldn't find the actual button entity, field, or whatever it is. @patrickkaleta Can you please tell us  where this include in report button is defined?

**Comment by patrickkaleta** [comment]
> The button is configured [here](https://csis.myclimateservice.eu/admin/structure/types/manage/gl_step/display/sce) in the respective GL Step, but I couldn't find the actual button entity, field, or whatever it is. @patrickkaleta Can you please tell us where this include in report button is defined?

The actual button is created as a "Token field" [here](https://csis.myclimateservice.eu/admin/structure/ds/fields/manage_token/include_in_report_button) via the Display suite module.

**Comment by p-a-s-c-a-l** [comment]
Another problem with the button which currently causes the ui integration tests to fail:

> Error: only one instance of babel-polyfill is allowed area line 2 > scriptElement:167:49465
    <anonym> https://csis.myclimateservice.eu/study/33/view/area line 2 > scriptElement:167
    <anonym> https://csis.myclimateservice.eu/study/33/view/area line 2 > scriptElement:167
    r https://csis.myclimateservice.eu/study/33/view/area line 2 > scriptElement:167
    <anonym> https://csis.myclimateservice.eu/study/33/view/area line 2 > scriptElement:167
    r https://csis.myclimateservice.eu/study/33/view/area line 2 > scriptElement:167
    <anonym> https://csis.myclimateservice.eu/study/33/view/area line 2 > scriptElement:167
    <anonym> https://csis.myclimateservice.eu/study/33/view/area line 2 > scriptElement:167

> TypeError: Drupal.editors is undefinedarea line 2 > scriptElement:103:5
    <anonym> https://csis.myclimateservice.eu/study/33/view/area line 2 > scriptElement:103
    <anonym> https://csis.myclimateservice.eu/study/33/view/area line 2 > scriptElement:209

When pressing the button on [this page](https://csis.myclimateservice.eu/study/33/view/area). Furthermore, the 'edit report image'  window is not shown which is probably related to the above errors.

**Comment by fgeyer16** [comment]
I just checked and found, that the "include in report Button" fails to post the imaget o Drupal. The ajax request fails with an 422 "Unprocessable Entity" Error. @patrickkaleta any changes in the content type or js?

> Furthermore, the 'edit report image' window is not shown which is probably related to the above errors.

When I check on click events on thebutton in Chromes Developer tools It seens if thereis an empty handler. But maybe this is the result of this errors. Who is using babel The map component?

**Comment by patrickkaleta** [comment]
> I just checked and found, that the "include in report Button" fails to post the imaget o Drupal. The ajax request fails with an 422 "Unprocessable Entity" Error. @patrickkaleta any changes in the content type or js?

No, no changes in entity or js. Drupal logs say that the error is caused, because the screenshot file already exists ([log message](https://csis.myclimateservice.eu/admin/reports/dblog/event/2463668)). These errors started occuring today at around 13:00.

**Comment by patrickkaleta** [comment]
> > I just checked and found, that the "include in report Button" fails to post the imaget o Drupal. The ajax request fails with an 422 "Unprocessable Entity" Error. @patrickkaleta any changes in the content type or js?
> 
> No, no changes in entity or js. Drupal logs say that the error is caused, because the screenshot file already exists ([log message](https://csis.myclimateservice.eu/admin/reports/dblog/event/2463668)). These errors started occuring today at around 13:00.

This was probably caused by the fact that some files on the server were removed after reverting to the state of yesterday (while the DB stayed the same). I created the missing files on the server by duplicating another report image (shouldn't really matter, since all those screenshots are still just from dummy studies).

Report images are now again being generated & stored properly.

**Comment by therter** [comment]
> Error: only one instance of babel-polyfill is allowed

This error is [solved](https://github.com/clarity-h2020/map-component/issues/88) now.

**Comment by therter** [comment]
> But perhaps we can add several include in report buttons for different parts the iFramed application?
> 
> for Scenario Analysis App we would just need atm the table and the bar charts.

The [Scenario Analysis page](https://csis.myclimateservice.eu/study/33/step/1517/view/scenario-analysis) has now two buttons to include the table and the chart in the report.

**Comment by p-a-s-c-a-l** [comment]
Layers from the group *CLARITY Backgrounds* selected [on this map](https://csis.myclimateservice.eu/study/131/step/3842/view/maps) do not appear in the [report image](https://csis.myclimateservice.eu/sites/default/files/report-images/2020-03/map-snapshot_120.png). This is probably caused by the fact that [TLS is still not available](https://github.com/clarity-h2020/csis/issues/120#issuecomment-603774614) for services.clarity-h2020.eu

**Comment by therter** [comment]
No Access-Control-Allow-Origin' header is present in the response from the wms http://services.clarity-h2020.eu:8080/geoserver/clarity/ows. So I have reopend [this issue](https://github.com/clarity-h2020/data-package/issues/50)

**Comment by p-a-s-c-a-l** [comment]
Again, not working on [this page](https://csis.myclimateservice.eu/study/25/step/3682/view/table) with FireFox 74.

![grafik](https://user-images.githubusercontent.com/1788226/78241793-460de200-74e1-11ea-8f06-55bd29e1c913.png)

**Comment by DenoBeno** [comment]
Taking screenshots works for everything expect for the CLARITY land use layers at my side. (Test with latest chrome)

If i get this correctly, the wms serving CLARITY land use layers is misconfigured. Missing the Access-Control-Allow-Origin or not having TLS configured. Whatever it is, we already have another server that's working OK, so we just need the same configuration as on that one (server with hazard layers), no?

Who is responsible for this server? Is it @ghilbrae ? If it's @negroscuro , I have just noticed that he isn't included in this conversation.

**Comment by therter** [comment]
> Again, not working on [this page](https://csis.myclimateservice.eu/study/25/step/3682/view/table) with FireFox 74.
> 
> ![grafik](https://user-images.githubusercontent.com/1788226/78241793-460de200-74e1-11ea-8f06-55bd29e1c913.png)

Thsi should be fixed now

**Comment by p-a-s-c-a-l** [comment]
![grafik](https://user-images.githubusercontent.com/1788226/78884282-f8522600-7a5a-11ea-9fb9-3e5bcc4597f9.png)

**Comment by p-a-s-c-a-l** [comment]
@therter what is the current status? Did you test it with Firefox, too? Windows or Linux?
- Firefox 75.0 (64-Bit) Windows 7: working
- Firefox 75.0 (64-Bit) Windows 10: not working

So probably a problem with the graphic card driver. Doesn't seem that we have any influence on that. 
I close the issue for now. We'll wait for the results of the technical validation: https://github.com/clarity-h2020/csis-technical-validation/issues/1

**Comment by p-a-s-c-a-l** [comment]
This is a never ending story. I tried to make a screenshot of [this](https://csis-dev.myclimateservice.eu/study/163/step/4896/view/maps) map, but it's again not working:

![](https://csis-dev.myclimateservice.eu/sites/default/files/report-images/2020-07/map-snapshot_87.jpg)

**Comment by therter** [comment]
The position of the popup from the GetFeatureInfo request is correct now (on the dev instance), but I could not reproduce the errors on the left map.

**Comment by p-a-s-c-a-l** [comment]
O.K. Thanks.
